### ISSUE TITLE
Please provide clear documentation

### ISSUE THREAD

**Issue by luisloaiza** [Criptext/react-monkey-ui#4]
We need more documentation and references here cc @GianniCarlo

**Comment by fluxny75** [comment]
@erikaperugachi and @GianniCarlo -- what is the action plan to have the documentation needed?
- When will you guys start?
- Do you have a goal to when we will have the first version of the documentation
- I suggest to assigned a milestone
- Will this documentation go in the website?

cc @luisloaiza

**Comment by GianniCarlo** [comment]
@fluxny75 The documentation process already started, it was decided that all the documentation will go in [GitBook](www.gitbook.com), probably the website/admin will link to it. As to when we will have the first version we first need to list what we're missing and coordinate with our current development as to not have any more delays. Currently we are lacking:
- [ ] Functions documentation
- [ ] Step by step tutorials on how to create a chat (akin to widget but not necessarily so) using the react components. ( @erikaperugachi can you split this item into a checklist? )

This last point should indicate what other possibilities there are when manipulating the components. @luisloaiza if there's something you want to add to that let us know.

Currently @erikaperugachi is in the midst of updating Criptext's private chat while also giving support to Carlos which just started with the integration today. @erikaperugachi please give us a more detailed checklist on the step by step tutorial so we can gauge what's missing and give a better estimate.

**Comment by fluxny75** [comment]
Looks like we have lots on our plates before we start with the documentation even so @GianniCarlo mention that we have started. can we set a time to put what we have today on **GitBook**.

Is important that we set milestones for all the task other wise we dont commit to it.

if we get time this week 6-04-2016 lets talk about this. please.

cc @luisloaiza
